export const products = [
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
  {
    img: "https://source.unsplash.com/random",
    name: "card",
    content: "content",
    like: 45,
    dislike: 10,
  },
];
